spring:
  application:
    name: demo-schedule-test
  
  # Database Configuration f端r Tests
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_demo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  
  # Email Configuration f端r Tests (MailHog)
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: false

# Logging f端r Tests
logging:
  level:
    root: INFO
    com.example.schedule: INFO
    org.springframework.mail: INFO

# Custom application properties f端r Tests
app:
  scheduling:
    enabled: false  # Scheduling in Tests deaktivieren
  email:
    from: test-noreply@example.com
    test-recipient: test@example.com